version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t yourdockerhubusername/flask-app:latest .
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push yourdockerhubusername/flask-app:latest

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "your:ssh:key:fingerprint"
      - run:
          name: SSH into Droplet and Deploy
          command: |
            ssh -o StrictHostKeyChecking=no youruser@your.droplet.ip "docker pull yourdockerhubusername/flask-app:latest && \
            docker stop flaskapp || true && docker rm flaskapp || true && \
            docker run -d --name flaskapp -p 80:80 yourdockerhubusername/flask-app:latest"


workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
